name: Deploy Project

on:
  push:
    branches: master

jobs:
  gh-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2.1.2
        with:
          node-version: '12.x'
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: '0.85.0'
      - name: Install and Build
        run: |
          git config --global user.email "mh97888@gmail.com"
          git config --global user.name "Azderica"
          npm ci
          npm run build
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.SECRET_KEY }}
          branch: gh-pages # The branch the action should deploy to.
          publish_branch: gh-pages
          publish_dir: build # The folder the action should deploy.
